name: Deploy Dev

on:
  push:
    branches: [dev, feature/*, update/*, fix/*]
  workflow_dispatch:

env:
  project_name: "yourclock-frontend"
  language: "javascript" #javascript, java, python
  branch_default: "dev"

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.branch.target=${{ env.branch_default }}
            -Dsonar.branch.name=${{ env.branch_default }}

  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install dependencies
        shell: bash
        run: npm ci
      - name: Build project
        shell: bash
        run: npm run build:dev
      - name: Upload build project
        uses: actions/upload-artifact@v3
        with:
          name: dist
          retention-days: 1
          path: dist

  deploy-netlify:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs: [build]
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download build of project
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_KEY }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
